import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'dev.architectury.loom' version '1.10-SNAPSHOT'
    id 'com.modrinth.minotaur' version '2.+'
    id 'net.darkhax.curseforgegradle' version '1.1.+'
}

group = project.maven_group
version = project.minecraft_version + "-" + project.mod_version

base {
    archivesName = project.archives_name
}

loom {
    silentMojangMappingsLicense()
}

repositories {
    maven { url 'https://jitpack.io' }
    maven {
        name 'ParchmentMC'
        url 'https://maven.parchmentmc.org'
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "net.minecraft:minecraft:$project.minecraft_version"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${project.parchment_version}@zip")
    }
    forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

java {
    withJavadocJar()
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 8
}

String[] supportedGameVersions = new String[]{"1.16.5"}
String currentChangeLog = file("CHANGELOG.md").getText("UTF-8")

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "${archives_name}"
    versionNumber = "${mod_version}"
    uploadFile = remapJar
    gameVersions.addAll(supportedGameVersions)
    loaders = ["forge"]
    versionType = "release"
    additionalFiles = [sourcesJar, javadocJar]
    changelog.set(currentChangeLog)
}

tasks.register("publishCurseForge", TaskPublishCurseForge) {
    apiToken = System.getenv("CURSEFORGE_TOKEN")
    disableVersionDetection()

    def mainFile = upload(cf_project_id, remapJar)
    mainFile.displayName = "${archives_name}-${version}"
    mainFile.releaseType = "release"
    mainFile.changelog = currentChangeLog
    mainFile.changelogType = "markdown"
    mainFile.addModLoader("Forge")
    mainFile.addJavaVersion("Java 17", "Java 8", "Java 21", "Java 22")
    mainFile.addGameVersion(supportedGameVersions)

    def sourcesFile = mainFile.withAdditionalFile(sourcesJar)
    def javadocFile = mainFile.withAdditionalFile(javadocJar)

    sourcesFile.changelog = currentChangeLog
    sourcesFile.changelogType = "markdown"
    javadocFile.changelog = currentChangeLog
    javadocFile.changelogType = "markdown"
}
