import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'dev.architectury.loom' version '1.10-SNAPSHOT'
    id 'com.modrinth.minotaur' version '2.+'
    id 'net.darkhax.curseforgegradle' version '1.1.+'
    id "com.github.johnrengelman.shadow" version "8.1.1"
}

group = project.maven_group
version = project.minecraft_version + "-" + project.mod_version

configurations {
    shadow
    implementation.extendsFrom(shadow)
}

base {
    archivesName = project.archives_name
}

loom {
    silentMojangMappingsLicense()

    forge {
        mixinConfig 'potacore.mixins.json'
    }
}

repositories {
    maven { url 'https://jitpack.io' }
    maven {
        name 'ParchmentMC'
        url 'https://maven.parchmentmc.org'
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "net.minecraft:minecraft:$project.minecraft_version"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${project.parchment_version}@zip")
    }
    forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
    shadow(annotationProcessor("io.github.llamalad7:mixinextras-common:${project.mixinextras_version}"))

    shadow(implementation("org.openjdk.jol:jol-core:0.17"))
}

shadowJar {
    configurations = [project.configurations.shadow]
    relocate "com.llamalad7.mixinextras", "me.kall.potacore.mixinextras"
    mergeServiceFiles()

    archiveClassifier = "dev-shadow"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

java {
    withSourcesJar()

    if (version.startsWith("1.16.5")) {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    } else {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

remapJar {
    dependsOn shadowJar
    inputFile = shadowJar.archiveFile
    archiveClassifier = null
}

tasks.withType(JavaCompile).configureEach {
    if (version.startsWith("1.16.5")) {
        it.options.release = 8
    } else {
        it.options.release = 17
    }
}

String currentChangeLog = file("CHANGELOG.md").getText("UTF-8")

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "${archives_name}"
    versionNumber = "${mod_version}"
    uploadFile = remapJar
    gameVersions.add(minecraft_version)
    loaders = ["forge"]
    versionType = "release"
    additionalFiles = [sourcesJar]
    changelog.set(currentChangeLog)
}

tasks.register("publishCurseForge", TaskPublishCurseForge) {
    apiToken = System.getenv("CURSEFORGE_TOKEN")
    disableVersionDetection()

    def mainFile = upload(cf_project_id, remapJar)
    mainFile.displayName = "${archives_name}-${version}"
    mainFile.releaseType = "release"
    mainFile.changelog = currentChangeLog
    mainFile.changelogType = "markdown"
    mainFile.addModLoader("Forge")
    mainFile.addJavaVersion("Java 17", "Java 8", "Java 21", "Java 22")
    mainFile.addGameVersion(minecraft_version)

    def sourcesFile = mainFile.withAdditionalFile(sourcesJar)

    sourcesFile.changelog = currentChangeLog
    sourcesFile.changelogType = "markdown"
}
