modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "potacore"
version = "${version}"
displayName = "Potacore"
authors = "TeamPotato"
description = '''
A Minecraft Mod.
'''